### ISSUE TITLE
Error when eslint can't find an .eslintrc

### ISSUE THREAD

**Issue by Thom1729** [SublimeLinter/SublimeLinter-eslint#211]
#### Steps to reproduce

1. Open a new window.
2. Set the syntax to `JavaScript`.

#### Result

The console opens and the following message is printed:

```
SublimeLinter: #154 eslint <untitled 718> ERROR:

 
Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /opt/sublime_text and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint


```

#### Environment

Sublime Text 3157, Linux x64.

---

This linter will try to invoke eslint on any JavaScript file. However, not every file or project has a lint configuration, and when none is present this package prints an error message on every modification. This can be very disruptive if the user is doing something with the console.

#### Possible solutions

- Silently ignore that particular eslint error.
- When that error is received, disable linting for that view.
- When that error is received, offer the user a choice (via dialog) to disable linting.
- Don't try to lint anonymous views.
- Check before linting whether a config file can be found and don't run the linter if none exists.
- Use a default eslint config when none can be found.

**Comment by braver** [comment]
> Use a default eslint config when none can be found.

You can do this yourself by adding an eslint config to your home dir.

**Comment by tricinel** [comment]
If you set up an empty .eslintrc in your home dir, it will indeed work. Just a simple

```json
{
  "rules": {}
}
```
will work fine. Previously however, we didn't have this problem. It's the latest updated to SL4 that caused this. Easy workaround, but should probably be in the docs somewhere. Troubleshooting maybe? I'm more than happy to add it if you find it useful.

**Comment by tricinel** [comment]
Yes, agreed. I figured it *might* have been broken before but never threw the error :)

No problem on the PR, doing it now, should be a quick add to the Readme actually.

**Comment by tricinel** [comment]
Added #213

**Comment by braver** [comment]
🎉 : https://github.com/SublimeLinter/SublimeLinter-eslint#ive-got-sublimelinter-eslint-error-eslint-couldnt-find-a-configuration-file-when-i-am-editing-a-javascript-file

**Comment by kaste** [comment]
Thank you @tricinel

**Comment by matteocontrini** [comment]
I'm not sure this is a solution. I've created the "global" .eslintrc file, but now the linter is complaining that `The keyword 'const' is reserved`, in the first line of every file, because that's an ES6 feature that is not enabled by default with the empty configuration file.

Can't you just ignore the error when the .eslintrc file is missing, instead of showing that popup? I believe that should be the default behaviour, without requiring every user to manually create a configuration file for getting rid of that popup...

It would also avoid eslint to be launched frequently for no reason, when there are no rules to enforce.

**Comment by Thom1729** [comment]
I agree. The workaround removes the error message from the console but adds spurious error regions. In addition, it's annoying to have to create a dummy global config file on every computer I run Sublime on.

**Comment by tricinel** [comment]
Hmm, if there was a way to have some sort of debug (true/false) and not pop open the console when false, that maybe could work. The errors would still be logged, but you would need to take an extra step to see them, kind of like debugger statements and the dev tools.

@matteocontrini, I'm not sure how you can ignore the error with the eslintrc is missing, because eslint searches recursively, starting from the same level as the file it's linting, all the way to the home directory. Where do you tell it to stop and decide there is no eslintrc? It's eslint that decides it crashes, not this plugin. This is just relaying the output from ESLint to you.

@Thom1729, how many computers do you have though so that it's a pain to create a file (that you could anyway automate with some dotfiles)? :)

**Comment by matteocontrini** [comment]
> It's eslint that decides it crashes, not this plugin. This is just relaying the output from ESLint to you.

Wouldn't it be an idea to parse that output and recognize when the error is related to the missing .eslintrc, and ignore the error in that case?

I still think that users shouldn't have to worry about touching configuration files just to avoid getting a popup every time a file is saved. It should just fail silently when there are no rules to lint against.

**Comment by tricinel** [comment]
I'll try to have a look this week. I'm also using this heavily myself every day, but I eslint every project I have at the moment so it's rarely an issue.

**Comment by kaste** [comment]
Re-open for visibility.

**Comment by kaste** [comment]
Any good ideas here? Obviously I don't like to suppress the error. It would be opt-in anyway. And then when 'everyone' has to touch the configuration of this plugin, they could as well create a dummy config file. 

Suppressing the error would also mean that eslint is still running all the time which is a complete waste. 

Now the question is: Can we guess a user intention to automatically *disable* eslint for that view, window, or session? Or must we ask the user to get the intention.

**Comment by tricinel** [comment]
As far as I'm concerned, there are two ways to enable/disable the linter, and none of them depend on this specific plugin.

1. On a per project basis, in `.sublime-project`.
2. Globally, in SublimeLinter's settings. And then enable as needed.

As to guessing the user's intention, I don't think we can do this reliably. We have API access to opened files, so we know the currently viewed file. We could traverse the tree upwards and if there is no eslint, don't display errors, but up to where?

Even so, can we tell SublimeLinter to disable a linter from a plugin? Or do we just ignore the error (not even ignore it, just don't show the console).

For individual files that you don't want linted? I'm not sure what to do. In an ideal world, we'd lint them on demand (meaning, linter is disabled and we manually say lint this view) - which is what I think option 2 above does.

**Comment by kaste** [comment]
FWIW 

- We can't implement the algo for finding the config file bc it is too complicated.
- Next SublimeLinter release will have a (hopefully) working version of the `disable_if_not_dependency` setting, which will enable (if set) this plugin only when eslint  is locally installed
- Next SublimeLinter will allow to exclude unsaved/anonymous views or generally files out of the current project

**Comment by Thom1729** [comment]
Is it possible to tell eslint to use a manually specified configuration as a fallback if it doesn't find another? If so, this would allow this package to bundle a no-op default configuration that the user could customize if desired.

**Comment by tricinel** [comment]
There's another thing to take into account here. If you have not installed eslint globally (npm install -g eslint or yarn global add eslint), then this error will not show up, even without that empty .eslintrc in your home directory.

I know eslint supports both local and global install (and so does this plugin). I try not to have global installs if I can help it, so maybe that's why I also run into this issue less frequently.

**Comment by kaste** [comment]
FWIW

- Next SublimeLinter update will popup this error once (per session/per window).

@tricinel Yes it is is really the combination here. Globally installed (user choice), globally enabled in Sublime Text (the default), but no global config (the default).

**Comment by arcman77** [comment]
"You can do this yourself by adding an eslint config to your home dir."

That is a hack.

**Comment by braver** [comment]
> That is a hack.

Not really. We throw any and all javascript files at eslint (unless configured otherwise) and having an eslint config in your home dir ensures it can always find a config. There is nothing hacky about that.

**Comment by aeisenberg** [comment]
Regarding this problem that @matteocontrini  mentioned:

> I'm not sure this is a solution. I've created the "global" .eslintrc file, but now the linter is complaining that The keyword 'const' is reserved, in the first line of every file, because that's an ES6 feature that is not enabled by default with the empty configuration file.

I was getting a similar problem where the call to eslint itself was failing. And once that happened, none of my js files were being linted. 

After a bit of frustration, I realized that somewhere on my system I still had v0.10 installed and this was being used to run eslint (instead of my user's nvm version of node).

I simply upgraded the global version and the eslinter is working fine now.

**Comment by tricinel** [comment]
This is another good reason why not have a global eslint (or global anything for that matter), when installing it locally is a simple `--save-dev` or `--dev` away and you always ensure it works as expected. You can even install node as a local dependency: https://www.npmjs.com/package/node.

I don't know...for me it's a non-issue. I can surely understand other's points of views though...

**Comment by jeremytm** [comment]
I'm getting this error on non-js files like html and php. I don't remember changing anything manually. But it seems to have happened since a update.

**Comment by tricinel** [comment]
@jeremytm, what's in your `SublimeLinter.sublime-settings` for your user for eslint?

Could you double-check the eslint in linters?

```
"linters": {
    "eslint": {
      "disable": false,
      "selector": "source.js", // <--- make sure you don't have html or anything else like that in there
      "args": [],
      "excludes": []
    }
}
```
Also that the correct syntax is set for the file...Hope this helps.

**Comment by jeremytm** [comment]
@tricinel the `linters` array is empty in the main settings file, and doesn't exist in the user settings; so it must be running off defaults. I can't say I've seen any errors come up for non-js files in the last few days, but it certainly happened and I confirmed the error message contained files names which ended in html, or php.

If it happens again I'll grab a screenshot.

**Comment by jeremytm** [comment]
ok, it happened again immediately after switching projects from a project which uses eslint, to a project which doesn't:
<img width="1196" alt="screen shot 2018-04-10 at 3 59 00 pm" src="https://user-images.githubusercontent.com/6539834/38535608-623ac7b0-3cd8-11e8-83a7-119be8bd1047.png">

How do I prevent eslint from running in projects in which I don't want it to run? i.e. projects in which I have never installed a config file?

**Comment by tricinel** [comment]
I would say, try to set the eslint prop in linters and see if it still happens.

**Comment by braver** [comment]
Configuration errors like this aren't invasive anymore.
