### ISSUE TITLE
SublimeLinter not recognize “jest/globals” env

### ISSUE THREAD

**Issue by djha-effendi** [SublimeLinter/SublimeLinter-eslint#279]
SublimeLinter-Eslint not working after a fresh install of react-native project.

`shell$ react-native init MyProject`

Error is "Environment key "jest/globals" is unknown"

Running eslint (comand line) not fired any error.

`shell$ eslint App.js`

Also by Using "Eslint" package (https://packagecontrol.io/packages/ESLint)

But the package "SublimeLinter-eslint" throw this error "Environment key "jest/globals" is unknown"

Any idea ?
Thanks

**Comment by kaste** [comment]
If you just started the project, maybe you have eslint >6 which is incompatible with this plugin (not for everything but partly).

Otherwise, please enable debug mode, then SublimeLinter will log a lot of information in Sublime's console `View > Show console`. You should see which eslint SublimeLinter actually picks here, and can compare that to your eslint on the cli. The working dir is usually also important to check.

**Comment by djha-effendi** [comment]
Yes it was the version 6 !
I downgraded to v 5.16.0 and ... it's works !

Thank you very much @kaste
