### ISSUE TITLE
Better eslint_d integration proposal

### ISSUE THREAD

**Issue by vitalyq** [SublimeLinter/SublimeLinter-eslint#297]
I have tried setting `"executable": "eslint_d"` in `SublimeLinter.sublime-settings` and it seems to work fine.

The only issue so far: when ESLint is not configured for a file, the error pops up:

```
SublimeLinter: #1 eslint file.js ERROR:
=============================================

JSON Decode error: We expected JSON from 'eslint', but instead got this:
Error: No ESLint configuration found in /path/to/repo.


Be aware that we only parse the last line of above output.
```

A similar issue is solved in SublimeLinter-eslint with `missing_config_regex`. eslint_d uses ESLint through API (`CLIEngine`), that's why the error message is different. Also, eslint_d outputs the message to stdout (not stderr), thus the error ends up in `find_errors`.

I propose these fixes:
- In eslint_d: output exceptions to stderr
- In SublimeLinter-eslint: filter `Error: No ESLint configuration found`

Is this an acceptable solution or am I missing something? (If it is, I'm ready to work on the implementation)

@mantoni your input is also greatly appreciated

**Comment by mantoni** [comment]
I'd happily merge a PR to send error output to stderr. 👍

**Comment by kaste** [comment]
Sounds good to me.

**Comment by mantoni** [comment]
@vitalyq Once you get it to run properly, I'd be thankful if you could share your findings here: https://github.com/mantoni/eslint_d.js/issues/120. Direct SublimeLinter integration through config would be great because we could remove the unmaintained Sublime plugin from the documentation.

**Comment by kaste** [comment]
I see how this becomes painful maybe, if a user sets `executable`, SublimeLinter bypasses to figure a good working dir or "project_root".  This usually leads to `--resolve-plugins-relative-to` errors.  Afair you don't need `--rprt` *if* you set the working dir following some algo we have implemented in `NodeLinter.find_local_executable`.  (Basically, as soon as you set `executable` you're in "I want full control" land, leave me alone.)

Actually, I always thought `eslint_d` is to be installed globally (once), and picks actual `eslint` installations (local or global ones) automatically.  In this case it's part of `eslint_d` to pick the correct `cwd` as well, at least *we* do both in `find_local_executable`, we find a local executable with the best base/project dir, because they're related. (Esp. different pacmans can put the executable at different places if they "hoist" a package up.)

**Comment by mantoni** [comment]
Yes, `eslint_d` is supposed to be installed globally, but works as a local install in the same way. It invokes eslint using `process.cwd()` on every invocation and resolves `eslint` from there using `require.resolve('eslint', { paths: [cwd] })`. If that doesn't work, it falls back to `require.resolve('eslint')`. In both cases eslint is configured to use the current working directory for the eslint config resolution to work.

**Comment by DimitrisRK** [comment]
I believe this setting should be mentioned in documentation, since package is quite slow without the use of eslint_d.

**Comment by Klaster1** [comment]
This might be a bit off topic, but I spent hours trying to make global eslint_d work with project-installed plugins. Setting the `"executable": "eslint_d"` causes `ensure_plugin_installed` to throw - _(2)_ - because of empty `project_root`.  What I found to help was this configuration:
```json
// SublimeLinter Settings - User
{
    "linters": {
        "eslint": {
            "selector": "source.ts",
        },
    }
}
```
This works because `ensure_plugin_installed` performs an early return - _(1)_ - when `selector` is set:
```python
def ensure_plugin_installed(self) -> bool:
    if self.settings['selector'] != OPTIMISTIC_SELECTOR:
        return True # (1)

    # skipped for brevity
    project_root = self.context.get('project_root')
    if project_root:
      # skipped for brevity

    self.notify_unassign()
    raise PermanentError() # (2)
```
I wish the above was metioned in the readme.

**Comment by kaste** [comment]
@Klaster1 Updated the README.  Technically, since the user set `executable` we never find a `package.json` and hence fallback to "Javascript" only.

**Comment by kaste** [comment]
I made a PR to use `eslint_d` automatically at #318
