### ISSUE TITLE
Excessive Tasks on Queue

### ISSUE THREAD

**Issue by nicholas-ochoa** [SublimeLinter/SublimeLinter-eslint#304]
I've noticed warnings on the ST console where the linter seems to be getting called excessively for file loads / modifications:

![image](https://user-images.githubusercontent.com/126299/99846054-47a51c80-2b3b-11eb-8e6b-f26d7c5c6628.png)

[full output](https://github.com/SublimeLinter/SublimeLinter-eslint/files/5575864/output.txt)

In this example there were 17 copies of the linter executed simultaneously. Usually it's less but I can't figure out any kind of pattern to it (sometimes 4 launch, sometimes 9 launch, etc..). I'm just opening files in the project and and soon as the tab is focused or a change made in the file tons of tasks are fired off.

I've tried increasing the background delay setting from 0.1 to 0.5 or even 1.0 but it doesn't seem to make a difference - the delay works but after 0.5 seconds I still see a bunch of ESLint tasks executing.

**Comment by kaste** [comment]
(Where is that double logging coming from? 🤔 )

We report these excessive tasks because sometimes the configuration might be not what you want.  `17(!)` is truly excessive.  Usually it comes from the `selector` setting.  I noticed eslint runs on an html file here, did you have `eslint-plugin-html` installed?  Or hav you changed the default `selector` in your settings?  (If you have 17 tasks on one html file it looks like it runs every `<script>` content through a separate eslint process. Just a guess.)

**Comment by nicholas-ochoa** [comment]
It appears to be worst on Angular component HTML files - your comment is pretty much spot on, it's the scope within the file that's causing the excessive number of ESLint instances. In this case, within the Angular component there were 17 separate areas that were scoped for TS/JS code and those were individually being sent for linting...at the same time. 

Is there a better or alternative way to have linting done in this case? In most cases it looks like ES Lint is getting spun up to lint a single one word variable or a simple condition.

**Comment by kaste** [comment]
Closing as this plugin now detects the `@angular-eslint/eslint-plugin` and configures the selector automatically.
